// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Warriors_Clinic.Models;

#nullable disable

namespace Warriors_Clinic.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Warriors_Clinic.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<DateTime?>("AppointmentDateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Criticality")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsVisibleToDoctor")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int");

                    b.Property<int?>("PhysicianId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ScheduleStatus")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("AppointmentId")
                        .HasName("PK__Appointm__8ECDFCC204B77562");

                    b.HasIndex("PatientId");

                    b.HasIndex("PhysicianId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Warriors_Clinic.Models.Chemist", b =>
                {
                    b.Property<int>("ChemistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ChemistID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChemistId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ChemistId");

                    b.ToTable("Chemists");
                });

            modelBuilder.Entity("Warriors_Clinic.Models.Drug", b =>
                {
                    b.Property<int>("DrugId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DrugID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DrugId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateOnly>("Expiry")
                        .HasColumnType("date");

                    b.Property<string>("Tittle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("DrugId");

                    b.ToTable("Drugs");
                });

            modelBuilder.Entity("Warriors_Clinic.Models.DrugRequest", b =>
                {
                    b.Property<int>("DrugRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DrugRequestId"));

                    b.Property<int?>("ChemistId")
                        .HasColumnType("int");

                    b.Property<string>("DrugInfoText")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsDeletedByPhysician")
                        .HasColumnType("bit");

                    b.Property<int?>("PhysicianId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RequestDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("RequestStatus")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("DrugRequestId")
                        .HasName("PK__DrugRequ__AEE9D630B65886DB");

                    b.HasIndex("ChemistId");

                    b.HasIndex("PhysicianId");

                    b.ToTable("DrugRequests");
                });

            modelBuilder.Entity("Warriors_Clinic.Models.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageId"));

                    b.Property<string>("MessageText")
                        .HasColumnType("text");

                    b.Property<int?>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<int?>("SenderId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("MessageId")
                        .HasName("PK__Messages__C87C0C9CDDBF30F9");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Warriors_Clinic.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PatientID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2")
                        .HasColumnName("DOB");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PatientId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("Warriors_Clinic.Models.Physician", b =>
                {
                    b.Property<int>("PhysicianId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PhysicianID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhysicianId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PhysicianId");

                    b.ToTable("Physicians");
                });

            modelBuilder.Entity("Warriors_Clinic.Models.PhysicianAdvice", b =>
                {
                    b.Property<int>("PhysicianAdviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhysicianAdviceId"));

                    b.Property<string>("Advice")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("PhysicianAdviceId")
                        .HasName("PK__Physicia__82C625F0D3DA4DB3");

                    b.ToTable("PhysicianAdvice");
                });

            modelBuilder.Entity("Warriors_Clinic.Models.PhysicianPrescription", b =>
                {
                    b.Property<int>("PrescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrescriptionId"));

                    b.Property<string>("Dosage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DrugId")
                        .HasColumnType("int");

                    b.Property<string>("Duration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PhysicianAdviceId")
                        .HasColumnType("int");

                    b.Property<string>("Prescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Timing")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PrescriptionId")
                        .HasName("PK__Physicia__40130832B582FABF");

                    b.HasIndex("DrugId");

                    b.HasIndex("PhysicianAdviceId");

                    b.ToTable("PhysicianPrescription");
                });

            modelBuilder.Entity("Warriors_Clinic.Models.PurchaseOrderHeader", b =>
                {
                    b.Property<int>("Poid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Poid"));

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Podate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Poid")
                        .HasName("PK__Purchase__5F02A2D45CDE26B8");

                    b.HasIndex("SupplierId");

                    b.ToTable("PurchaseOrderHeader");
                });

            modelBuilder.Entity("Warriors_Clinic.Models.PurchaseOrderLine", b =>
                {
                    b.Property<int>("PolineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PolineId"));

                    b.Property<int?>("DrugId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Poid")
                        .HasColumnType("int");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("PolineId")
                        .HasName("PK__Purchase__07B9D3621DB03421");

                    b.HasIndex("DrugId");

                    b.HasIndex("Poid");

                    b.ToTable("PurchaseOrderLine");
                });

            modelBuilder.Entity("Warriors_Clinic.Models.Schedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsSent")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ScheduleDate")
                        .HasColumnType("datetime");

                    b.Property<int>("ScheduleStatus")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("int");

                    b.HasKey("ScheduleId")
                        .HasName("PK__Schedule__9C8A5B495BE3D830");

                    b.HasIndex("AppointmentId");

                    b.ToTable("Schedule");
                });

            modelBuilder.Entity("Warriors_Clinic.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SupplierID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("SupplierId");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("Warriors_Clinic.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("ReferenceToId")
                        .HasColumnType("int")
                        .HasColumnName("ReferenceToId");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Warriors_Clinic.Models.Appointment", b =>
                {
                    b.HasOne("Warriors_Clinic.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .HasConstraintName("FK__Appointme__Patie__5812160E");

                    b.HasOne("Warriors_Clinic.Models.Physician", "Physician")
                        .WithMany("Appointments")
                        .HasForeignKey("PhysicianId")
                        .HasConstraintName("FK__Appointme__Physi__59063A47");

                    b.Navigation("Patient");

                    b.Navigation("Physician");
                });

            modelBuilder.Entity("Warriors_Clinic.Models.DrugRequest", b =>
                {
                    b.HasOne("Warriors_Clinic.Models.Chemist", "Chemist")
                        .WithMany()
                        .HasForeignKey("ChemistId");

                    b.HasOne("Warriors_Clinic.Models.Physician", "Physician")
                        .WithMany("DrugRequests")
                        .HasForeignKey("PhysicianId")
                        .HasConstraintName("FK__DrugReque__Physi__66603565");

                    b.Navigation("Chemist");

                    b.Navigation("Physician");
                });

            modelBuilder.Entity("Warriors_Clinic.Models.Message", b =>
                {
                    b.HasOne("Warriors_Clinic.Models.User", "Receiver")
                        .WithMany("MessageReceivers")
                        .HasForeignKey("ReceiverId")
                        .HasConstraintName("FK__Messages__Receiv__72C60C4A");

                    b.HasOne("Warriors_Clinic.Models.User", "Sender")
                        .WithMany("MessageSenders")
                        .HasForeignKey("SenderId")
                        .HasConstraintName("FK__Messages__Sender__71D1E811");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Warriors_Clinic.Models.PhysicianPrescription", b =>
                {
                    b.HasOne("Warriors_Clinic.Models.Drug", "Drug")
                        .WithMany("PhysicianPrescriptions")
                        .HasForeignKey("DrugId")
                        .HasConstraintName("FK__Physician__DrugI__628FA481");

                    b.HasOne("Warriors_Clinic.Models.PhysicianAdvice", "PhysicianAdvice")
                        .WithMany("PhysicianPrescriptions")
                        .HasForeignKey("PhysicianAdviceId")
                        .HasConstraintName("FK__Physician__Physi__619B8048");

                    b.Navigation("Drug");

                    b.Navigation("PhysicianAdvice");
                });

            modelBuilder.Entity("Warriors_Clinic.Models.PurchaseOrderHeader", b =>
                {
                    b.HasOne("Warriors_Clinic.Models.Supplier", "Supplier")
                        .WithMany("PurchaseOrderHeaders")
                        .HasForeignKey("SupplierId")
                        .HasConstraintName("FK__PurchaseO__Suppl__6A30C649");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Warriors_Clinic.Models.PurchaseOrderLine", b =>
                {
                    b.HasOne("Warriors_Clinic.Models.Drug", "Drug")
                        .WithMany("PurchaseOrderLines")
                        .HasForeignKey("DrugId")
                        .HasConstraintName("FK__PurchaseO__DrugI__6E01572D");

                    b.HasOne("Warriors_Clinic.Models.PurchaseOrderHeader", "PurchaseOrderHeader")
                        .WithMany("PurchaseOrderLines")
                        .HasForeignKey("Poid")
                        .HasConstraintName("FK__PurchaseOr__Poid__6D0D32F4");

                    b.Navigation("Drug");

                    b.Navigation("PurchaseOrderHeader");
                });

            modelBuilder.Entity("Warriors_Clinic.Models.Schedule", b =>
                {
                    b.HasOne("Warriors_Clinic.Models.Appointment", "Appointment")
                        .WithMany("Schedules")
                        .HasForeignKey("AppointmentId")
                        .HasConstraintName("FK__Schedule__Appoin__5BE2A6F2");

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("Warriors_Clinic.Models.Appointment", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("Warriors_Clinic.Models.Drug", b =>
                {
                    b.Navigation("PhysicianPrescriptions");

                    b.Navigation("PurchaseOrderLines");
                });

            modelBuilder.Entity("Warriors_Clinic.Models.Patient", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Warriors_Clinic.Models.Physician", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("DrugRequests");
                });

            modelBuilder.Entity("Warriors_Clinic.Models.PhysicianAdvice", b =>
                {
                    b.Navigation("PhysicianPrescriptions");
                });

            modelBuilder.Entity("Warriors_Clinic.Models.PurchaseOrderHeader", b =>
                {
                    b.Navigation("PurchaseOrderLines");
                });

            modelBuilder.Entity("Warriors_Clinic.Models.Supplier", b =>
                {
                    b.Navigation("PurchaseOrderHeaders");
                });

            modelBuilder.Entity("Warriors_Clinic.Models.User", b =>
                {
                    b.Navigation("MessageReceivers");

                    b.Navigation("MessageSenders");
                });
#pragma warning restore 612, 618
        }
    }
}
